### ISSUE TITLE
unRAID - all folder and backups set to owner "UNKNOWN" after backup runs.

### ISSUE THREAD

**Issue by Tyree** [tiredofit/docker-db-backup#359] opened 2024-08-11 13:13 UTC
### Summary

Each time a backup runs, it sets all folders and files to owner "UNKOWN".

### Steps to reproduce

Run a backup

### What is the expected *correct* behavior?

Ability to set the owner ID, not just the permissions, so it is defined and not UNKNOWN

### Environment
![Screenshot 2024-08-11 093821](https://github.com/user-attachments/assets/81f47c3d-791b-4c4d-8f08-0b1b306c3025)
![Screenshot 2024-08-11 093848](https://github.com/user-attachments/assets/7055aefe-f56e-4966-a509-094cb1231efb)

- Image version / tag:  latest
- Host OS: unRAID

**Comment by tiredofit** [comment] 2024-08-11 19:11
I'm not familiar with this template, nor is it supported from this repository, closing as this is not a bug.

**Closed by tiredofit** 2024-08-11 19:11 UTC
Labels: bug
